### ISSUE TITLE
Language support - update

### ISSUE THREAD

**Issue by sp39chorzow** [bartoszek/AUR-openboard-develop-git#1]
Hello, can you update your scripts to fix language support in Arch/Manjaro?
Issue details here: https://github.com/OpenBoard-org/OpenBoard/issues/472
Many thanks!

**Comment by bartoszek** [comment]
Should be fixed now (tested on ArchLinux)
![Zrzut ekranu z 2021-04-14 15-15-05](https://user-images.githubusercontent.com/1213348/114717687-94310480-9d35-11eb-95b7-39a1b3ad2bd0.png)
btw. as `dev-qt5.1x` was merged into master this package is redundant and will be dropped, you should switch to `openboard-develop` for version `1.6.1rc` or `openboard-git` for the current github master.
_Pozdro z Krakowa_ ౦０o ｡ (‾́。‾́ )y~~
